# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1smtFb8YKFQSjPBcxj_3x01Og_T4lUxEP
"""

import requests
import json



#Automatizar o processo de levantar a cotação de moedas


requisicao_dolar = requests.get("https://economia.awesomeapi.com.br/all/USD-BRL")
requisicao_euro = requests.get("https://economia.awesomeapi.com.br/all/EUR-BRL")
requisicao_libra = requests.get("https://economia.awesomeapi.com.br/all/GBP-BRL")
requisicao_bitcoin = requests.get("https://economia.awesomeapi.com.br/all/BTC-BRL")

#Para adicionar mais moedas basta alterar o "USD-BRL" para a conversão que você deseja no final da url da awesomeapi

cotacao_dolar = requisicao_dolar.json()
cotacao_euro = requisicao_euro.json()
cotacao_libra = requisicao_libra.json()
cotacao_bitcoin = requisicao_bitcoin.json()

cotacao_dolar 
print("Cotação do euro")
print ("Moeda: " + cotacao_dolar["USD"]["name"])
print("Valor atual: R$" + cotacao_dolar["USD"]["bid"])
print ("Data: " + cotacao_dolar["USD"]["create_date"])

print("***")

cotacao_euro
print("Cotação do Euro")
print ("Moeda: " + cotacao_euro["EUR"]["name"])
print("Valor atual: R$" + cotacao_euro["EUR"]["bid"])
print ("Data: " + cotacao_euro["EUR"]["create_date"])

print("***")

cotacao_libra
print("Cotação da Libra Estelina")
print ("Moeda: " + cotacao_libra["GBP"]["name"])
print("Valor atual: R$" + cotacao_libra["GBP"]["bid"])
print ("Data: " + cotacao_libra["GBP"]["create_date"])

print("***")

cotacao_bitcoin
print("Cotação do Bitcoin")
print ("Moeda: " + cotacao_bitcoin["BTC"]["name"])
print("Valor atual: R$" + cotacao_bitcoin["BTC"]["bid"])
print ("Data: " + cotacao_bitcoin["BTC"]["create_date"])

